services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Map your app's port
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092  # Point to the Kafka service
    depends_on:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest  # Use the official Confluent Zookeeper image
    ports:
      - "2181:2181"  # Map Zookeeper port
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  kafka:
    image: confluentinc/cp-kafka:latest  # Use the official Confluent Kafka image
    ports:
      - "9092:9092"  # Map Kafka port
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9094

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8081:8080"  # Expose Kafka UI on port 8081
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
